language: python
python:
  - "2.7"
install:
  - pip install tox
script:
  - tox
deploy:
  provider: pypi
  user: amancevice
  password:
    secure: immmfueytliDL7buFISKkUtuIqSKcYHh6tl0QArXQWF7Cm7TG6EKShZpAOVnrdgWbgOwSEaM8f/kqLxTX1OX3rPG8rUVuJp4WY0J9qO3NSomHer0mS8PjoZLqd7MwnJ6wjMFb6eUL/YFyi656md66Xv2qHDhmTikFOTZK57lKJZuPiqEQBoMN2LM6Z+11PZ8z+cwHshDXLyu6RJ5BY9MfwE8Oop1Cx18DVefWLhfCXVVuVpsHr0b6UrBxb9WTPJygmLQUBOV9waZsIZhG54AWarrFkPROP8EbgJXfW2nbiCnGybr8ikxhBPBj0S1ieKP36CklpIa7KVyGXjzfwW1PEyJjwTbvnRZYprJW1ODyyHnHUF4z+JrR9DgodmNYQe8vagn+RaZedV4edyFHx03BDfatNhcjiH9pjPptvOvygQBYa/k+OA5J7DYNnqBDdf6tXolQBeO+knmIIDsG+W6T3y6QN2EbWS3SbPMTa2nT3hjmrVJGFZ19GqEKSuxnHb659j6x1U684lr/BCOrUbPqiGh37TQ+b9mSm922Ayg2mcsEwEDs+1QZcWOhfxmlCLtyRdTP/jBa/ewzVrEl+WzJ0tppDkNvzztQA0X/NhsrwC3+JGNPSHV4hrjMllLzKOF98ubDlcC+kz4A66UuzEmYukQ/1E0yOr9Qo8zHgPNc+Y=
  on:
    tags: true
    distributions: sdist
    repo: amancevice/pline
